name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Change this to the branch you want to deploy from

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'

    # install composer require vlucas/phpdotenv
    - name: Install Composer Dependencies
      run: composer install 
      

    - name: Access API Token and Deploy
      run: php backend/api.php
      env:
        GITHUB_API_TOKEN: ${{ secrets.API_TOKEN }}

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.API_TOKEN }}
        publish_dir: ./frontend